title: Efficiency Aggregators
baseurl: /ea-static
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
base_font: nunito-sans
palette: green
header:
  logo_img: images/branding/EfficiencyAggregators_1.png
  logo_img_alt: Logo
  has_nav: true
  nav_links:
    - label: Home
      url: /
      style: link
    - label: Residential
      url: /residential
      style: link
    - label: Commercial & Industrial
      url: /commercial-industrial
      style: link
    - label: Biotech
      url: /biophotoreactor
      style: link
    - label: Contact Us
      url: /contact
      style: primary
footer:
  sections:
    - type: footer_text
      image: images/branding/square-logo.png
      image_url: /
      image_alt: Footer logo
    - type: footer_nav
      title: Company
      nav_links:
        - label: About Us
          url: /about
          style: link
        - label: Contact
          url: /contact
          style: link
    - type: footer_nav
      title: Community
      nav_links:
        - label: Facebook
          url: 'https://www.facebook.com/efficiencyaggregators'
          style: link
          has_icon: true
          icon: facebook
          icon_position: left
        - label: LinkedIn
          url: 'https://www.linkedin.com/company/efficiency-aggregators/'
          style: link
          has_icon: true
          icon: linkedin
          icon_position: left
        # - label: Twitter
        #   url: 'https://twitter.com'
        #   style: link
        #   has_icon: true
        #   icon: twitter
        #   icon_position: left
    - type: footer_text
      title: Our Details
      content: >-
        - **Email**  
          [contactus@efficiencyaggregators.com](mailto:contactus@efficiencyaggregators.com)

          **Phone**  
          [832-862-1103](tel:+1-832-862-1103)

          **Fax**  
          [832-558-4602](tel:+1-832-558-4602)

          **Address**  
          [1207 Farm to Market 359
          Richmond, TX 77406](geo:29.61260903500409,-95.74363544048104)
## TODO - abstract this out so address and api key aren't hardcoded
    - type: section_gmaps
      section_id: gmap
      title: Find Us

  has_nav: true
  nav_links:
    - label: Terms of Service
      url: /terms-of-service
      style: link
    - label: Privacy Policy
      url: /privacy-policy
      style: link
  content: >-
    &copy; Stackbit. All rights reserved. This Jamstack site was created with <a
    href="https://www.stackbit.com/?utm_source=deployed-footer" target="_blank"
    rel="noopener">Stackbit</a>. Create yours <a
    href="https://app.stackbit.com/create?theme=azimuth&utm_source=deployed-footer"
    target="_blank" rel="noopener">now</a>.
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
